import { RiskLevel } from '../enums/risk-level';
import type { TriageMessage } from './triage';

/**
 * ClinicalIntake — AI-assisted structured clinical data collection.
 * Extends the concept of TriageSession with deeper clinical structuring.
 * Compatible with chat-agents backend (Onboarding + Symptoms agents).
 */
export interface ClinicalIntake {
  id: string;
  citizenId: string;
  unitId: string;

  // Chat interaction (reuses TriageMessage format for chat-backend compatibility)
  messages: TriageMessage[];

  // Structured clinical data extracted by AI
  chiefComplaint: string;
  symptoms: string[];
  symptomDuration?: string;
  symptomOnset?: string;
  associatedSymptoms?: string[];
  painScale?: number; // 0-10
  vitalSigns?: {
    bloodPressure?: string;
    heartRate?: number;
    temperature?: number;
    oxygenSaturation?: number;
    respiratoryRate?: number;
  };

  // Patient context
  currentMedications?: string[];
  allergies?: string[];
  chronicConditions?: string[];
  recentHospitalizations?: string;
  familyHistory?: string[];

  // Social determinants (relevant for public health)
  socialVulnerabilityScore?: number; // 0-10
  hasBasicSanitation?: boolean;
  housingCondition?: 'ADEQUATE' | 'PRECARIOUS' | 'HOMELESS';
  incomeLevel?: 'NO_INCOME' | 'UP_TO_1MW' | '1_TO_3MW' | 'ABOVE_3MW';

  // AI classification output
  riskLevel: RiskLevel;
  priorityScore: number; // 0-100
  clinicalSummary?: ClinicalSummary;
  examSuggestions?: ExamSuggestion[];
  referralRecommendation?: ReferralRecommendation;

  // Lifecycle
  isComplete: boolean;
  startedAt: string;
  completedAt?: string;
}

/**
 * Structured clinical summary generated by the Structuring Agent.
 * Designed to be sent to specialists as a pre-consultation package.
 */
export interface ClinicalSummary {
  id: string;
  intakeId: string;
  narrative: string; // AI-generated clinical narrative
  structuredFindings: string[]; // Key findings as bullet points
  suspectedConditions: string[]; // Differential diagnoses suggested by AI
  cid10Codes?: string[]; // CID-10 codes for suspected conditions
  relevantHistory: string; // Filtered relevant medical history
  riskFactors: string[]; // Identified risk factors
  generatedAt: string;
}

/**
 * AI-suggested exams before specialist consultation.
 * Reduces unnecessary referrals by ensuring data is ready.
 */
export interface ExamSuggestion {
  id: string;
  intakeId: string;
  examName: string;
  examCode?: string; // SIGTAP code for SUS
  category: 'LABORATORY' | 'IMAGING' | 'FUNCTIONAL' | 'OTHER';
  priority: 'URGENT' | 'ROUTINE';
  justification: string; // AI reasoning for suggesting this exam
  status: 'SUGGESTED' | 'REQUESTED' | 'COMPLETED' | 'CANCELLED';
  result?: string;
  completedAt?: string;
}

/**
 * AI-generated referral recommendation.
 * Core feature: should the patient be resolved at UBS or referred?
 */
export interface ReferralRecommendation {
  id: string;
  intakeId: string;
  decision: 'RESOLVE_PRIMARY' | 'REFER_SPECIALIST' | 'REFER_EMERGENCY' | 'NEEDS_MORE_DATA';
  confidence: number; // 0-100
  specialty?: string; // Target specialty if referring
  justification: string; // AI reasoning
  requiredExamsBeforeReferral: string[]; // Exams that should be done before referring
  alternativeActions?: string[]; // What primary care can try first
  generatedAt: string;
}
