# Backend configuration for platform stack - HML
bucket         = "trya-terraform-state"
key            = "hml/platform/terraform.tfstate"
region         = "sa-east-1"
encrypt        = true
dynamodb_table = "trya-terraform-locks"
profile        = "skopia"
