# Backend configuration for chat-agents stack - DEV
bucket         = "trya-terraform-state"
key            = "dev/chat-agents/terraform.tfstate"
region         = "sa-east-1"
encrypt        = true
dynamodb_table = "trya-terraform-locks"
profile        = "skopia"
