# Backend configuration for network stack - DEV
bucket         = "trya-terraform-state"
key            = "dev/network/terraform.tfstate"
region         = "sa-east-1"
encrypt        = true
dynamodb_table = "trya-terraform-locks"
profile        = "skopia"
