import type { HealthDocument } from "@/types/family-health"

export const categoryLabels = {
  "lab-results": "Exames Laboratoriais",
  "medical-images": "Imagens Médicas",
  vaccination: "Vacinação",
  "clinical-files": "Arquivos Clínicos",
  "routine-checkup": "Check-ups",
}

export const mockHealthDocuments: HealthDocument[] = [
  {
    id: "1",
    memberId: "1",
    title: "Hemograma Completo",
    category: "lab-results",
    date: new Date("2024-01-15"),
    expiryDate: new Date("2024-07-15"),
    author: "Dr. Carlos Santos",
    clinic: "Laboratório Central",
    fileType: "PDF",
    fileSize: 245760,
    secureLink: "/api/documents/secure/1",
    accessLevel: "private",
    description: "Exame de sangue de rotina para check-up anual",
    tags: ["rotina", "sangue", "check-up"],
    status: "valid",
    priority: "medium",
    results: [
      { key: "Hemoglobina", value: "12.5", unit: "g/dL", normalRange: "12.0-15.5", status: "normal" },
      { key: "Leucócitos", value: "7200", unit: "/mm³", normalRange: "4000-11000", status: "normal" },
      { key: "Plaquetas", value: "280000", unit: "/mm³", normalRange: "150000-450000", status: "normal" },
    ],
  },
  {
    id: "2",
    memberId: "1",
    title: "Colesterol Total",
    category: "lab-results",
    date: new Date("2023-11-20"),
    expiryDate: new Date("2024-05-20"),
    author: "Dr. Maria Oliveira",
    clinic: "Laboratório Saúde+",
    fileType: "PDF",
    fileSize: 180240,
    secureLink: "/api/documents/secure/2",
    accessLevel: "private",
    description: "Perfil lipídico completo",
    tags: ["colesterol", "lipídios", "cardiovascular"],
    status: "expired",
    priority: "high",
    results: [
      { key: "Colesterol Total", value: "220", unit: "mg/dL", normalRange: "<200", status: "abnormal" },
      { key: "HDL", value: "45", unit: "mg/dL", normalRange: ">40", status: "normal" },
      { key: "LDL", value: "140", unit: "mg/dL", normalRange: "<100", status: "abnormal" },
    ],
    reminders: [
      {
        type: "retest",
        date: new Date("2024-02-20"),
        message: "Repetir exame de colesterol",
      },
    ],
  },
  {
    id: "3",
    memberId: "2",
    title: "Raio-X Tórax",
    category: "medical-images",
    date: new Date("2024-01-10"),
    author: "Dr. Ana Costa",
    clinic: "Hospital São Lucas",
    fileType: "DICOM",
    fileSize: 1048576,
    secureLink: "/api/documents/secure/3",
    accessLevel: "private",
    description: "Exame de imagem do tórax para investigação de tosse persistente",
    tags: ["imagem", "tórax", "respiratório"],
    status: "valid",
    priority: "medium",
    thumbnailUrl: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "4",
    memberId: "3",
    title: "Vacina COVID-19 - 1ª Dose",
    category: "vaccination",
    date: new Date("2023-12-20"),
    author: "Enfermeira Paula",
    clinic: "UBS Centro",
    fileType: "PDF",
    fileSize: 102400,
    secureLink: "/api/documents/secure/4",
    accessLevel: "public",
    description: "Primeira dose da vacina COVID-19 - Pfizer",
    tags: ["vacina", "covid", "pfizer"],
    status: "valid",
    priority: "high",
    reminders: [
      {
        type: "vaccination",
        date: new Date("2024-02-20"),
        message: "Segunda dose da vacina COVID-19",
      },
    ],
  },
  {
    id: "5",
    memberId: "3",
    title: "Consulta Pediátrica",
    category: "routine-checkup",
    date: new Date("2024-01-05"),
    author: "Dr. Pedro Lima",
    clinic: "Clínica Infantil",
    fileType: "PDF",
    fileSize: 156800,
    secureLink: "/api/documents/secure/5",
    accessLevel: "private",
    description: "Consulta de rotina pediátrica - desenvolvimento normal",
    tags: ["pediatria", "rotina", "desenvolvimento"],
    status: "valid",
    priority: "low",
    notes: "Criança apresenta desenvolvimento adequado para a idade. Recomendado retorno em 6 meses.",
  },
  {
    id: "6",
    memberId: "2",
    title: "Ultrassom Abdominal",
    category: "medical-images",
    date: new Date("2023-12-15"),
    author: "Dr. Roberto Silva",
    clinic: "Centro de Diagnóstico",
    fileType: "PDF",
    fileSize: 512000,
    secureLink: "/api/documents/secure/6",
    accessLevel: "private",
    description: "Ultrassonografia abdominal total",
    tags: ["ultrassom", "abdomen", "diagnóstico"],
    status: "valid",
    priority: "medium",
    thumbnailUrl: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "7",
    memberId: "1",
    title: "Mamografia",
    category: "medical-images",
    date: new Date("2023-10-30"),
    expiryDate: new Date("2024-10-30"),
    author: "Dr. Carla Mendes",
    clinic: "Centro da Mulher",
    fileType: "DICOM",
    fileSize: 2048000,
    secureLink: "/api/documents/secure/7",
    accessLevel: "private",
    description: "Mamografia bilateral de rastreamento",
    tags: ["mamografia", "prevenção", "mama"],
    status: "valid",
    priority: "high",
    thumbnailUrl: "/placeholder.svg?height=100&width=100",
  },
  {
    id: "8",
    memberId: "3",
    title: "Vacina Tríplice Viral",
    category: "vaccination",
    date: new Date("2023-11-10"),
    author: "Enfermeira Sandra",
    clinic: "UBS Centro",
    fileType: "PDF",
    fileSize: 98304,
    secureLink: "/api/documents/secure/8",
    accessLevel: "public",
    description: "Vacina contra sarampo, caxumba e rubéola",
    tags: ["vacina", "tríplice", "viral"],
    status: "valid",
    priority: "medium",
  },
]
