// Dependency injection tokens for the Chat module
export const TENANT_REPOSITORY_TOKEN = 'TENANT_REPOSITORY';
export const BEDROCK_REPOSITORY_TOKEN = 'BEDROCK_REPOSITORY';
export const MEDICAL_IMAGE_REPOSITORY_TOKEN = 'MEDICAL_IMAGE_REPOSITORY';
export const SESSION_REPOSITORY_TOKEN = 'SESSION_REPOSITORY';
export const CHAT_SERVICE_TOKEN = 'CHAT_SERVICE';