export const FILE_PARSER_SERVICE_TOKEN = 'FILE_PARSER_SERVICE';
export const DATE_PARSER_SERVICE_TOKEN = 'DATE_PARSER_SERVICE';
export const PLAN_MANAGEMENT_SERVICE_TOKEN = 'PLAN_MANAGEMENT_SERVICE';
export const PLAN_VALIDATION_SERVICE_TOKEN = 'PLAN_VALIDATION_SERVICE';
export const HEALTH_OPERATORS_REPOSITORY_TOKEN = 'HEALTH_OPERATORS_REPOSITORY';
export const HEALTH_PLANS_REPOSITORY_TOKEN = 'HEALTH_PLANS_REPOSITORY';
